<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- <parent>
        <groupId>com.acanx.meta</groupId>
        <artifactId>meta-bom</artifactId>
        <version>${revision}</version>
    </parent> -->
    <groupId>com.acanx.meta.bom</groupId>
    <artifactId>bom-aio-origin</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>BOM-AIO-Origin</name>
    <description>BOM-AIO-Origin POM</description>
    <url>https://github.com/ACANX/MetaOpen</url>

    <scm>
        <tag>V0.8.x</tag>
        <url>git@github.com:ACANX/MetaOpen.git</url>
        <connection>scm:git:git@github.com:ACANX/MetaOpen.git</connection>
        <developerConnection>scm:git:git@github.com:ACANX/MetaOpen.git</developerConnection>
    </scm>
    <organization>
        <name>ACANX</name>
        <url>https://acanx.com</url>
    </organization>
    <developers>
        <developer>
            <name>ACANX</name>
            <email>acanx@qq.com</email>
            <organization>ACANX</organization>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
          <revision>0.8.9</revision>
          <!-- 将此属性设置为 true，即可跳过该模块的 deploy 阶段 -->
          <maven.deploy.skip>true</maven.deploy.skip>
          <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
          <bom-graalvm.version>25.0.8.9</bom-graalvm.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.acanx.meta</groupId>
                <artifactId>os-dependencies</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.acanx.meta.bom</groupId>
                <artifactId>bom-deamon</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.acanx.meta.bom</groupId>
                <artifactId>bom-mod</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.acanx.meta.bom</groupId>
                <artifactId>bom-sdk</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.acanx.meta.bom</groupId>
                <artifactId>bom-cf</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.acanx.meta.component</groupId>
                <artifactId>bom-graalvm</artifactId>
                <version>${bom-graalvm.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <compilerVersion>${java.version}</compilerVersion>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.7.3</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>bom</flattenMode>
                    <pomElements>
                        <parent>remove</parent>
                        <dependencyManagement>expand</dependencyManagement>
                        <properties>remove</properties>
                        <developers>keep</developers>
                        <scm>keep</scm>
                        <url>keep</url>
                        <organization>keep</organization>
                        <name>keep</name>
                        <description>keep</description>
                        <repositories>remove</repositories>
                    </pomElements>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
